### ISSUE TITLE
No Unique identifier For events Table

### ISSUE THREAD

**Issue by SimranBhagwandasani** [SimranBhagwandasani/EventPlanner#7]
@rahul-bhatia For events table, I can't see any unique identifier. The object_id generated by Mongo won't be a good measure to access the events while booking them. 
I'll strongly suggest to update the schema and an unique identifier before writing orders table.

**Comment by rahul-bhatia** [comment]
Not a big deal, mere couple lines of code. Ill get this done by tonight.

**Comment by SimranBhagwandasani** [comment]
Okay, Its sorted.
